#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if "$GH" auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if "$GH" auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=7
ENV_FILE="${ENV_FILE:-.scratch/wizards/.activity-schedule.env}"
REPO="emkataumre/portfolio"
REPO_URL="https://github.com/emkataumre/portfolio.git"
TASK_NAME="portfolio-activity"
BOT_NAME="activity-bot"
BOT_EMAIL="activity-bot@users.noreply.github.com"

# Not every bash on Windows ships cygpath, so convert paths here. to_unix
# turns "C:\a\b" into a slash path. to_win turns a slash path back.
to_unix() {
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -u "$1"
    return
  fi
  local p="${1//\\//}"
  local drive="${p%%:*}"
  local rest="${p#*:}"
  if [ "$drive" = "$p" ]; then
    printf "%s\n" "$p"
    return
  fi
  drive="${drive,,}"
  if [ -d "/mnt/$drive" ]; then
    printf "/mnt/%s%s\n" "$drive" "$rest"
  else
    printf "/%s%s\n" "$drive" "$rest"
  fi
}

# git runs the credential helper through sh, and sh cannot run a path that
# holds backslashes. The mixed form works in sh and in Windows.
to_mixed() {
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -m "$1"
    return
  fi
  local w
  w="$(to_win "$1")"
  printf "%s\n" "${w//\\//}"
}

to_win() {
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -w "$1"
    return
  fi
  local p="$1"
  p="${p#/mnt}"
  local drive="${p:1:1}"
  local rest="${p:2}"
  drive="${drive^^}"
  printf "%s:%s\n" "$drive" "${rest//\//\\}"
}

# Some bash sessions do not export LOCALAPPDATA. Fall back to the profile
# path, then ask Windows. Stop with a clear message if all three fail.
APPDATA_WIN="${LOCALAPPDATA:-}"
if [ -z "$APPDATA_WIN" ] && [ -n "${USERPROFILE:-}" ]; then
  APPDATA_WIN="${USERPROFILE}\\AppData\\Local"
fi
if [ -z "$APPDATA_WIN" ]; then
  APPDATA_WIN="$(cmd.exe /c 'echo %LOCALAPPDATA%' 2>/dev/null | tr -d '\r')"
fi
if [ -z "$APPDATA_WIN" ] || [ "$APPDATA_WIN" = "%LOCALAPPDATA%" ]; then
  echo "The wizard cannot find your local application data folder." >&2
  echo "Set LOCALAPPDATA and start the wizard again." >&2
  exit 1
fi

# The job clone lives outside the working clone. Windows tools need the
# backslash form, and bash needs the slash form.
APPDATA_UNIX="$(to_unix "$APPDATA_WIN")"
CLONE_WIN="${APPDATA_WIN}\\portfolio-activity"
CLONE_UNIX="$APPDATA_UNIX/portfolio-activity"
LOG_UNIX="$CLONE_UNIX/activity.log"

# gh is not always on the PATH, so look in the standard install folders
# too. Every stage calls gh through $GH.
BS="\\"
GH="gh"
if ! command -v gh >/dev/null 2>&1; then
  for candidate in \n    "$(to_unix "${PROGRAMFILES:-C:\Program Files}")/GitHub CLI/gh.exe" \n    "$(to_unix "${PROGRAMFILES:-C:\Program Files}") (x86)/GitHub CLI/gh.exe" \n    "$APPDATA_UNIX/Programs/GitHub CLI/gh.exe" \n    "$APPDATA_UNIX/Microsoft/WinGet/Links/gh.exe" \n    "${HOME:-}/scoop/shims/gh.exe"; do
    if [ -x "$candidate" ]; then
      GH="$candidate"
      PATH="$(dirname "$candidate"):$PATH"
      export PATH
      break
    fi
  done
fi

# Check the commands the stages need. Report every missing one at once.
MISSING=()
command -v "$GH" >/dev/null 2>&1 || [ -x "$GH" ] || MISSING+=("gh")
for cmd in git powershell.exe; do
  command -v "$cmd" >/dev/null 2>&1 || MISSING+=("$cmd")
done
if [ ${#MISSING[@]} -gt 0 ]; then
  echo "The wizard needs these commands on the PATH: ${MISSING[*]}" >&2
  echo "Install the missing command, or start Git Bash again to pick up a" >&2
  echo "PATH change, and then start the wizard again." >&2
  exit 1
fi

banner "Activity job: clone, bot identity, and Task Scheduler (issue #29)"

# -- 1 ---------------------------------------------------------------------
stage "Create the job clone"
say "The job runs in its own clone, away from your working clone."
say "    Working clone: I:\\Personal\\portfolio  (do not touch)"
say "    Job clone:     $CLONE_WIN"
say ""
if [[ -d "$CLONE_UNIX/.git" ]]; then
  say "The clone is already there. Current remote and head:"
  git -C "$CLONE_UNIX" remote -v | sed 's/^/    /'
  git -C "$CLONE_UNIX" log --oneline -n 1 | sed 's/^/    /'
  if confirm "Reset it to origin/main now?"; then
    git -C "$CLONE_UNIX" fetch origin
    git -C "$CLONE_UNIX" reset --hard origin/main
    say "${GREEN}OK${RESET} the clone is on origin/main."
  fi
elif [[ -e "$CLONE_UNIX" ]]; then
  warn "$CLONE_WIN exists and is not a git clone."
  say "Move that directory, or delete it."
  say "Then start this wizard again."
  SKIPPED+=("create the job clone at $CLONE_WIN")
else
  say "This clones $REPO_URL into $CLONE_WIN."
  if confirm "Clone it now?"; then
    git clone "$REPO_URL" "$CLONE_UNIX"
    say "${GREEN}OK${RESET} cloned."
  else
    SKIPPED+=("create the job clone at $CLONE_WIN")
  fi
fi
write_env CLONE_DIR "$CLONE_WIN"
pause

# -- 2 ---------------------------------------------------------------------
stage "Set the bot identity in the job clone"
say "The bot identity is local config in the job clone only."
say "    user.name  = $BOT_NAME"
say "    user.email = $BOT_EMAIL"
warn "This must never run in your working clone. That clone keeps"
warn "user.email=emo.vladinov@gmail.com and no local user.name."
say ""
if [[ -d "$CLONE_UNIX/.git" ]]; then
  git -C "$CLONE_UNIX" config --local user.name "$BOT_NAME"
  git -C "$CLONE_UNIX" config --local user.email "$BOT_EMAIL"
  say "Job clone identity now:"
  git -C "$CLONE_UNIX" config --local --get user.name | sed 's/^/    user.name  = /'
  git -C "$CLONE_UNIX" config --local --get user.email | sed 's/^/    user.email = /'
  say ""
  # git prints a drive letter path and CLONE_UNIX is a slash path, so the
  # comparison needs both names in the same style.
  WORK_CLONE="$(git rev-parse --show-toplevel 2>/dev/null || true)"
  [[ -n "$WORK_CLONE" ]] && WORK_CLONE="$(to_unix "$WORK_CLONE")"
  if [[ -n "$WORK_CLONE" && "$WORK_CLONE" != "$CLONE_UNIX" ]]; then
    say "Working clone identity, unchanged:"
    git -C "$WORK_CLONE" config --local --get user.email | sed 's/^/    user.email = /' || say "    none"
  fi
else
  warn "no job clone yet, so the identity is not set."
  SKIPPED+=("set the bot identity in $CLONE_WIN")
fi
pause

# -- 3 ---------------------------------------------------------------------
stage "Check that both GitHub accounts hold a token"
say "The collector reads one token per account with 'gh auth token --user <login>'."
say "Both accounts must already hold a token in Windows Credential Manager."
say "A scheduled run has no browser. Log in now, by hand."
say ""
"$GH" auth status 2>&1 | sed 's/^/    /' || true
say ""
say "The list above must show 'emkataumre' and 'emil-the-second'."
say "If one login is missing, run this command."
note "    gh auth login --hostname github.com --git-protocol https --web"
say "Then start this wizard again."
pause "Do both accounts hold a token?"

# -- 4 ---------------------------------------------------------------------
stage "Check the token that the push uses"
say "The job pushes to main with the token of the emkataumre account."
say "The wrapper reads the token with 'gh auth token' and puts it in one"
say "request header. No token reaches a file, and no git config changes."
say ""

# An earlier version of this wizard wrote a credential helper here. git runs a
# helper through sh, and the sh on this machine cannot run a Windows path.
if [[ -d "$CLONE_UNIX/.git" ]]   && git -C "$CLONE_UNIX" config --local --get-regexp '^credential' >/dev/null 2>&1; then
  git -C "$CLONE_UNIX" config --local --remove-section 'credential.https://github.com'     >/dev/null 2>&1 || true
  note "Removed the credential helper that an earlier run wrote."
fi

PUSH_OK=0
if PUSH_TOKEN="$("$GH" auth token --user emkataumre 2>/dev/null)"   && [[ -n "$PUSH_TOKEN" ]]; then
  say "${GREEN}OK${RESET} gh holds a token for emkataumre."
  if [[ -d "$CLONE_UNIX/.git" ]]; then
    PUSH_HEADER="AUTHORIZATION: basic $(printf 'x-access-token:%s' "$PUSH_TOKEN" | base64 -w0)"
    say "Testing the push path without pushing anything:"
    if GIT_TERMINAL_PROMPT=0 git -C "$CLONE_UNIX" -c "http.extraheader=$PUSH_HEADER"       push --dry-run origin main 2>&1 | sed 's/^/    /'; then
      say "${GREEN}OK${RESET} the job clone can push to main."
      PUSH_OK=1
    else
      warn "The dry run failed. Correct the login before you register the task."
    fi
    PUSH_HEADER=""
  fi
else
  warn "gh holds no token for emkataumre."
  note "    $GH auth login --hostname github.com --git-protocol https --web"
  SKIPPED+=("log in as emkataumre")
fi
PUSH_TOKEN=""
pause

# -- 5 ---------------------------------------------------------------------
stage "Register the scheduled task"
say "Task name:  $TASK_NAME"
say "Runs:       12:00 and 17:00, local time, every day"
say "Runs as:    your own Windows account, while you are logged on"
say "Time limit: 10 minutes. A measured run took 76 seconds."
say "Action:     powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass"
say "            -File $CLONE_WIN\\scripts\\activity-job.ps1"
say ""
note "The task needs no password. It runs with your profile loaded, so gh"
note "can read Windows Credential Manager."
note "A run that falls while you are signed out starts at your next sign in,"
note "because -StartWhenAvailable is set."
note "-WakeToRun is not set, so the task never wakes a sleeping laptop."
note "-AllowStartIfOnBatteries is set, or every run on battery power is skipped."
say ""
REGISTER_PS1="$APPDATA_UNIX/portfolio-activity-register-task.ps1"
cat > "$REGISTER_PS1" <<'PS1_EOF'
$ErrorActionPreference = 'Stop'
$clone = Join-Path $env:LOCALAPPDATA 'portfolio-activity'
$wrapper = Join-Path $clone 'scripts\activity-job.ps1'
if (-not (Test-Path -LiteralPath $wrapper)) {
    throw "The wrapper is missing at $wrapper. Reset the job clone to origin/main first."
}
$action = New-ScheduledTaskAction -Execute 'powershell.exe' `
    -Argument "-NoProfile -NonInteractive -ExecutionPolicy Bypass -File `"$wrapper`""
$triggers = @(
    (New-ScheduledTaskTrigger -Daily -At 12:00),
    (New-ScheduledTaskTrigger -Daily -At 17:00)
)
# New-ScheduledTaskSettingsSet defaults DisallowStartIfOnBatteries and
# StopIfGoingOnBatteries to true. This job runs on a laptop, so those two
# defaults would skip every run that starts on battery power.
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -RunOnlyIfNetworkAvailable `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10)
# An Interactive principal needs no stored password. The task runs while the
# user is logged on, with the profile loaded, so gh can read Windows
# Credential Manager. A stored password does not work for an AzureAD account.
# Task Scheduler cannot map an AzureAD name to a security id, so the principal
# carries the security id of the current user.
$sid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value
$principal = New-ScheduledTaskPrincipal -UserId $sid -LogonType Interactive -RunLevel Limited
Register-ScheduledTask -TaskName 'portfolio-activity' -Action $action -Trigger $triggers `
    -Settings $settings -Principal $principal -Force | Out-Null
Get-ScheduledTask -TaskName 'portfolio-activity' | Format-List TaskName, State
PS1_EOF
TASK_REGISTERED=0
if confirm "Register the task now?"; then
  if powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(to_win "$REGISTER_PS1")"; then
    say "${GREEN}OK${RESET} the task is registered."
    TASK_REGISTERED=1
  else
    warn "The register script failed. The message above names the cause."
    SKIPPED+=("register the scheduled task $TASK_NAME")
  fi
else
  SKIPPED+=("register the scheduled task $TASK_NAME")
fi
rm -f "$REGISTER_PS1"
write_env TASK_NAME "$TASK_NAME"
pause

# -- 6 ---------------------------------------------------------------------
stage "Start the task once and check the result"
say "This starts the task by hand and waits for it to stop."
say "The first run collects every number again."
say "Wait about two minutes."
say ""
if [[ "$TASK_REGISTERED" -eq 0 ]]; then
  warn "The task is not registered, so the wizard skips the test run."
  SKIPPED+=("start $TASK_NAME once by hand")
elif confirm "Start $TASK_NAME now?"; then
  powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Start-ScheduledTask -TaskName '$TASK_NAME'; do { Start-Sleep -Seconds 5 } while ((Get-ScheduledTask -TaskName '$TASK_NAME').State -eq 'Running'); Get-ScheduledTaskInfo -TaskName '$TASK_NAME' | Format-List TaskName, LastRunTime, LastTaskResult" | sed 's/^/    /'
  say ""
  say "Last log line:"
  tail -n 1 "$LOG_UNIX" 2>/dev/null | sed 's/^/    /' || warn "no log file at $LOG_UNIX"
  say ""
  say "Head of the job clone:"
  git -C "$CLONE_UNIX" log --oneline -n 3 2>/dev/null | sed 's/^/    /' || true
  say ""
  say "Expect one of these three words in the log line:"
  say "    PUSHED    a number moved, and an 'activity: <date>' commit is on main"
  say "    NOCHANGE  no number moved, so the run committed nothing. This is a pass."
  say "    FAIL      the log line names the cause. Correct it and start the task again."
else
  SKIPPED+=("start $TASK_NAME once and check the result")
fi
pause

# -- 7 ---------------------------------------------------------------------
stage "Report the result on issue #29"
ask FIRST_RUN "Type the outcome word from the log line (PUSHED, NOCHANGE or FAIL):"
write_env FIRST_RUN "$FIRST_RUN"
COMMENT="Scheduled task \`$TASK_NAME\` is registered. Job clone: \`$CLONE_WIN\`. It runs at 12:00 and 17:00 local time. The first manual run reported \`$FIRST_RUN\`. The log is at \`%LOCALAPPDATA%\\portfolio-activity\\activity.log\`."
say "Comment text:"
say "    $COMMENT"
if confirm "Post this comment on $REPO issue #29?"; then
  "$GH" issue comment 29 --repo "$REPO" --body "$COMMENT"
  say "${GREEN}OK${RESET} posted."
else
  SKIPPED+=("post the first run result on issue #29")
fi
say ""
note "Check the commit list on main in a day. Two 'activity: <date>' commits"
note "from scheduled runs close the last box on the issue."
pause

finish
