#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=7
ENV_FILE="${ENV_FILE:-.scratch/wizards/.activity-schedule.env}"
REPO="emkataumre/portfolio"
REPO_URL="https://github.com/emkataumre/portfolio.git"
TASK_NAME="portfolio-activity"
BOT_NAME="activity-bot"
BOT_EMAIL="activity-bot@users.noreply.github.com"

# The job clone lives outside the working clone. Windows tools need the
# backslash form, and bash needs the slash form.
CLONE_WIN="${LOCALAPPDATA}\\portfolio-activity"
CLONE_UNIX="$(cygpath -u "$LOCALAPPDATA")/portfolio-activity"
LOG_UNIX="$(cygpath -u "$LOCALAPPDATA")/portfolio-activity/activity.log"

banner "Activity job: clone, bot identity, and Task Scheduler (issue #29)"

# -- 1 ---------------------------------------------------------------------
stage "Create the job clone"
say "The job runs in its own clone, away from your working clone."
say "    Working clone: I:\\Personal\\portfolio  (do not touch)"
say "    Job clone:     $CLONE_WIN"
say ""
if [[ -d "$CLONE_UNIX/.git" ]]; then
  say "The clone is already there. Current remote and head:"
  git -C "$CLONE_UNIX" remote -v | sed 's/^/    /'
  git -C "$CLONE_UNIX" log --oneline -n 1 | sed 's/^/    /'
  if confirm "Reset it to origin/main now?"; then
    git -C "$CLONE_UNIX" fetch origin
    git -C "$CLONE_UNIX" reset --hard origin/main
    say "${GREEN}OK${RESET} the clone is on origin/main."
  fi
elif [[ -e "$CLONE_UNIX" ]]; then
  warn "$CLONE_WIN exists and is not a git clone."
  say "Move it or delete it, then run this wizard again."
  SKIPPED+=("create the job clone at $CLONE_WIN")
else
  say "This clones $REPO_URL into $CLONE_WIN."
  if confirm "Clone it now?"; then
    git clone "$REPO_URL" "$CLONE_UNIX"
    say "${GREEN}OK${RESET} cloned."
  else
    SKIPPED+=("create the job clone at $CLONE_WIN")
  fi
fi
write_env CLONE_DIR "$CLONE_WIN"
pause

# -- 2 ---------------------------------------------------------------------
stage "Set the bot identity in the job clone"
say "The bot identity is local config in the job clone only."
say "    user.name  = $BOT_NAME"
say "    user.email = $BOT_EMAIL"
warn "This must never run in your working clone. That clone keeps"
warn "user.email=emo.vladinov@gmail.com and no local user.name."
say ""
if [[ -d "$CLONE_UNIX/.git" ]]; then
  git -C "$CLONE_UNIX" config --local user.name "$BOT_NAME"
  git -C "$CLONE_UNIX" config --local user.email "$BOT_EMAIL"
  say "Job clone identity now:"
  git -C "$CLONE_UNIX" config --local --get user.name | sed 's/^/    user.name  = /'
  git -C "$CLONE_UNIX" config --local --get user.email | sed 's/^/    user.email = /'
  say ""
  say "Working clone identity, unchanged:"
  git -C "$(git rev-parse --show-toplevel)" config --local --get user.email | sed 's/^/    user.email = /'
else
  warn "no job clone yet, so the identity is not set."
  SKIPPED+=("set the bot identity in $CLONE_WIN")
fi
pause

# -- 3 ---------------------------------------------------------------------
stage "Check that both GitHub accounts are logged in"
say "The collector reads one token per account with 'gh auth token --user <login>'."
say "Both accounts must already hold a token in Windows Credential Manager."
say "A scheduled run has no browser, so the login must happen now, by hand."
say ""
gh auth status 2>&1 | sed 's/^/    /' || true
say ""
say "The list above must show 'emkataumre' and 'emil-the-second'."
say "If one is missing, run this command and come back:"
note "    gh auth login --hostname github.com --git-protocol https --web"
pause "Are both accounts logged in?"

# -- 4 ---------------------------------------------------------------------
stage "Set up the git credential helper for the push"
say "'gh auth setup-git' makes git push through the gh credential helper,"
say "which reads Windows Credential Manager. No token is written to disk."
say ""
if confirm "Run 'gh auth setup-git' now?"; then
  gh auth setup-git --hostname github.com
  say "${GREEN}OK${RESET} the helper is set up."
else
  SKIPPED+=("run gh auth setup-git")
fi
say ""
if [[ -d "$CLONE_UNIX/.git" ]]; then
  say "Testing the push path without pushing anything:"
  if git -C "$CLONE_UNIX" push --dry-run origin main 2>&1 | sed 's/^/    /'; then
    say "${GREEN}OK${RESET} the job clone can push to main."
  else
    warn "the dry run failed. Fix the login before you register the task."
  fi
fi
pause

# -- 5 ---------------------------------------------------------------------
stage "Register the scheduled task"
say "Task name:  $TASK_NAME"
say "Runs:       12:00 and 17:00, local time, every day"
say "Runs as:    your own Windows account, logged on or not, stored password"
say "Time limit: 10 minutes. A measured run took 76 seconds."
say "Action:     powershell.exe -File $CLONE_WIN\\scripts\\activity-job.ps1"
say ""
note "A stored password is needed. Without it the task runs with no user"
note "profile, and gh cannot read Windows Credential Manager."
note "-WakeToRun is not set, so the task never wakes a sleeping laptop."
say ""
REGISTER_PS1="$(cygpath -u "$LOCALAPPDATA")/portfolio-activity-register-task.ps1"
cat > "$REGISTER_PS1" <<'PS1_EOF'
$ErrorActionPreference = 'Stop'
$clone = Join-Path $env:LOCALAPPDATA 'portfolio-activity'
$script = Join-Path $clone 'scripts\activity-job.ps1'
if (-not (Test-Path -LiteralPath $script)) {
    throw "The wrapper is missing at $script. Pull main in the job clone first."
}
$action = New-ScheduledTaskAction -Execute 'powershell.exe' `
    -Argument "-NoProfile -NonInteractive -ExecutionPolicy Bypass -File `"$script`""
$triggers = @(
    (New-ScheduledTaskTrigger -Daily -At 12:00),
    (New-ScheduledTaskTrigger -Daily -At 17:00)
)
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -RunOnlyIfNetworkAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10)
$user = "$env:USERDOMAIN\$env:USERNAME"
Write-Host ""
Write-Host "Type the Windows password for $user. Task Scheduler stores it."
$password = Read-Host 'Password'
Register-ScheduledTask -TaskName 'portfolio-activity' -Action $action -Trigger $triggers `
    -Settings $settings -User $user -Password $password -RunLevel Limited -Force | Out-Null
$password = $null
Get-ScheduledTask -TaskName 'portfolio-activity' | Format-List TaskName, State
PS1_EOF
if confirm "Register the task now?"; then
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(cygpath -w "$REGISTER_PS1")"
  say "${GREEN}OK${RESET} the task is registered."
else
  SKIPPED+=("register the scheduled task $TASK_NAME")
fi
rm -f "$REGISTER_PS1"
write_env TASK_NAME "$TASK_NAME"
pause

# -- 6 ---------------------------------------------------------------------
stage "Start the task once and check the result"
say "This starts the task by hand and waits for it to stop."
say "The first run collects every number again, so give it about two minutes."
say ""
if confirm "Start $TASK_NAME now?"; then
  powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Start-ScheduledTask -TaskName '$TASK_NAME'; do { Start-Sleep -Seconds 5 } while ((Get-ScheduledTask -TaskName '$TASK_NAME').State -eq 'Running'); Get-ScheduledTaskInfo -TaskName '$TASK_NAME' | Format-List TaskName, LastRunTime, LastTaskResult" | sed 's/^/    /'
  say ""
  say "Last log line:"
  tail -n 1 "$LOG_UNIX" 2>/dev/null | sed 's/^/    /' || warn "no log file at $LOG_UNIX"
  say ""
  say "Head of the job clone:"
  git -C "$CLONE_UNIX" log --oneline -n 3 2>/dev/null | sed 's/^/    /' || true
  say ""
  say "Expect one of these three words in the log line:"
  say "    PUSHED    a number moved, and an 'activity: <date>' commit is on main"
  say "    NOCHANGE  no number moved, so the run committed nothing. This is a pass."
  say "    FAIL      read the rest of the log line and fix the cause"
else
  SKIPPED+=("start $TASK_NAME once and check the result")
fi
pause

# -- 7 ---------------------------------------------------------------------
stage "Report the result on issue #29"
ask FIRST_RUN "Type the outcome word from the log line (PUSHED, NOCHANGE or FAIL):"
write_env FIRST_RUN "$FIRST_RUN"
COMMENT="Scheduled task \`$TASK_NAME\` is registered. Job clone: \`$CLONE_WIN\`. It runs at 12:00 and 17:00 local time. The first manual run reported \`$FIRST_RUN\`. The log is at \`%LOCALAPPDATA%\\portfolio-activity\\activity.log\`."
say "Comment text:"
say "    $COMMENT"
if confirm "Post this comment on $REPO issue #29?"; then
  gh issue comment 29 --repo "$REPO" --body "$COMMENT"
  say "${GREEN}OK${RESET} posted."
else
  SKIPPED+=("post the first run result on issue #29")
fi
say ""
note "Check the commit list on main in a day. Two 'activity: <date>' commits"
note "from scheduled runs close the last box on the issue."
pause

finish
