#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE="${ENV_FILE:-.scratch/wizards/.cloudflare-pages.env}"
REPO="emkataumre/portfolio"
BRANCH="deploy-cloudflare-pages"

banner "Cloudflare Pages setup (issue #13)"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "Merge the headers branch into main"
say "The first Pages deploy builds main. main must hold public/_headers first."
say "This merges $BRANCH into main with fast-forward only, then pushes."
note "Current state:"
git -C "$(git rev-parse --show-toplevel)" log --oneline "main..$BRANCH" | sed 's/^/    /'
if confirm "Merge $BRANCH into main and push?"; then
  git checkout main
  git merge --ff-only "$BRANCH"
  git push origin main
  say "${GREEN}✓${RESET} main is pushed."
else
  SKIPPED+=("merge $BRANCH into main and push")
  warn "skipped. The live headers check in stage 3 will fail until main has public/_headers."
fi
pause

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "Create the Pages project"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages/create/pages"
step "If the page asks, sign in and pick your account."
step "Pages tab → 'Connect to Git' (or 'Import an existing Git repository')."
step "Sign in with GitHub. Grant access to '$REPO' only. Click 'Install & Authorize'."
step "Select '$REPO' → 'Begin setup'."
say ""
say "Fill the build settings exactly like this:"
say "    Project name:            your choice (this becomes <name>.pages.dev)"
say "    Production branch:       main"
say "    Framework preset:        React (Vite)"
say "    Build command:           npm run build"
say "    Build output directory:  dist"
say "    Root directory:          leave empty"
say "    Environment variables:   none"
note "Node version comes from .nvmrc (22). The v3 build image reads it."
step "Click 'Save and Deploy'. Wait for the first build to reach 'Success'."
ask PAGES_PROJECT "Type the project name you chose:"
write_env PAGES_PROJECT "$PAGES_PROJECT"

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "Check the live site"
LIVE="https://${PAGES_PROJECT}.pages.dev"
say "Probing $LIVE"
say ""
say "Home page:"
curl -sI "$LIVE/" | grep -iE '^(HTTP|x-content-type-options|x-frame-options|referrer-policy|permissions-policy)' | sed 's/^/    /'
say ""
say "Build Log page:"
curl -sI "$LIVE/build-log/" | grep -iE '^HTTP' | sed 's/^/    /'
say ""
say "Redirect for /build-log (spec expects 307 to /build-log/):"
curl -sI "$LIVE/build-log" | grep -iE '^(HTTP|location)' | sed 's/^/    /'
say ""
say "Asset cache rule (first hashed asset):"
ASSET=$(curl -s "$LIVE/" | grep -oE '/assets/[^"]+\.js' | head -n1 || true)
if [[ -n "$ASSET" ]]; then
  curl -sI "$LIVE$ASSET" | grep -iE '^(HTTP|cache-control)' | sed 's/^/    /'
else
  warn "no /assets/*.js reference found in the home page HTML"
fi
say ""
say "Expected: four security headers on /, 200 on both pages, a 3xx with"
say "Location /build-log/ on the bare path, and Cache-Control immutable on the asset."
open_url "$LIVE/"
step "Open the browser devtools console on / and on /build-log/. Both must be empty."
pause "All good?"

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "Confirm PR previews are on"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Open the '$PAGES_PROJECT' project → Settings → Builds & deployments."
step "Under 'Preview branch control' confirm 'All non-Production branches' (the default)."
note "With that setting, every PR against main gets its own preview URL."
pause "Confirmed?"

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "Post the project name on issue #13"
say "Later tickets replace <project> with this name. It goes on the issue."
COMMENT="Pages project: \`${PAGES_PROJECT}\`. Production URL: ${LIVE}/"
say "Comment text:"
say "    $COMMENT"
if confirm "Post this comment on $REPO issue #13?"; then
  gh issue comment 13 --repo "$REPO" --body "$COMMENT"
  say "${GREEN}✓${RESET} posted."
else
  SKIPPED+=("post the project name on issue #13")
fi
say ""
note "Tick the acceptance boxes on the issue yourself once you are happy with stage 3."
pause

finish
