#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: complete the public launch checks for issue #33.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

PUBLIC_URL="https://portfolio-2mj.pages.dev"
REPO_URL="https://github.com/emkataumre/portfolio"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RECEIPT_FILE="$REPO_ROOT/.scratch/issue-33-launch-receipt.md"
VERIFICATION_NAME=""

record() {
  local gate="$1" status="$2" evidence="$3"
  evidence=${evidence//|/\\|}
  printf '| %s | %s | %s | %s |\n' \
    "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$gate" "$status" "$evidence" >> "$RECEIPT_FILE"
}

fail() {
  local gate="$1" evidence="$2"
  record "$gate" "failed" "$evidence"
  warn "$evidence"
  say "This gate failed. Fix it, then start the wizard again."
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Local prerequisites" "Required command is missing: $1"
}

status_code() {
  curl -sS -o /dev/null -w '%{http_code}' "$1"
}

require_200() {
  local url="$1" code
  code=$(status_code "$url")
  [[ "$code" == "200" ]] || fail "Live HTTP checks" "$url returned HTTP $code"
  say "HTTP 200: $url"
}

require_404() {
  local url="$1" code
  code=$(status_code "$url")
  [[ "$code" == "404" ]] || return 1
}

mkdir -p "$(dirname "$RECEIPT_FILE")"
cat > "$RECEIPT_FILE" <<EOF
# Issue #33 launch receipt

Generated by `.scratch/wizards/search-console-launch.sh`.

Status meanings:

- `verified`: this run checked the result or Emil confirmed it in the named account.
- `failed`: a required check failed. Do not close issue #33.
- `accepted`: Emil explicitly accepted a deferral. Issue #33 currently has no accepted deferrals.
- `pending`: the action still needs account access or human confirmation.

| Time UTC | Gate | Status | Evidence |
|---|---|---|---|
EOF

for gate in \
  "Search Console property" \
  "Verification file" \
  "Build and deployment" \
  "Search Console ownership" \
  "Sitemap" \
  "URL Inspection" \
  "Bing import" \
  "LinkedIn profile" \
  "GitHub profile" \
  "Live quality checks" \
  "Retired routes" \
  "Map and issue closure"
do
  record "$gate" "pending" "Not completed yet."
done

cd "$REPO_ROOT"
require_command git
require_command npm
require_command curl
require_command rg

banner "Portfolio search and launch"

stage "Create the Search Console property"
say "This site uses a URL-prefix property because pages.dev DNS is not yours."
open_url "https://search.google.com/search-console"
step "Open the property selector."
step "Select Add property."
step "Choose URL prefix."
step "Enter exactly: $PUBLIC_URL/"
step "Select Continue."
step "Under HTML file, select the download button. Do not edit the file."
confirm "Has Google downloaded the verification HTML file?" || \
  fail "Search Console property" "Google did not download the verification file."
record "Search Console property" "verified" "URL-prefix property created for $PUBLIC_URL/ and HTML file selected."

stage "Place the exact verification file"
say "The verification token must come from Google. This wizard does not create one."
ask VERIFICATION_SOURCE "Enter the downloaded file path (Git Bash path or drag the file here):"
VERIFICATION_SOURCE=${VERIFICATION_SOURCE#\"}
VERIFICATION_SOURCE=${VERIFICATION_SOURCE%\"}
[[ -f "$VERIFICATION_SOURCE" ]] || fail "Verification file" "The downloaded file does not exist: $VERIFICATION_SOURCE"
VERIFICATION_NAME=$(basename "$VERIFICATION_SOURCE")
[[ "$VERIFICATION_NAME" =~ ^google[[:alnum:]_-]+\.html$ ]] || \
  fail "Verification file" "Unexpected file name: $VERIFICATION_NAME"
EXPECTED_LINE="google-site-verification: $VERIFICATION_NAME"
ACTUAL_LINE=$(tr -d '\r\n' < "$VERIFICATION_SOURCE")
[[ "$ACTUAL_LINE" == "$EXPECTED_LINE" ]] || \
  fail "Verification file" "The file content does not match its Google verification file name."
DESTINATION="$REPO_ROOT/public/$VERIFICATION_NAME"
if [[ -f "$DESTINATION" ]]; then
  cmp -s "$VERIFICATION_SOURCE" "$DESTINATION" || \
    fail "Verification file" "A different file already exists at public/$VERIFICATION_NAME"
  say "The exact Google file is already in public/."
else
  confirm "Copy the downloaded file unchanged to public/$VERIFICATION_NAME?" || \
    fail "Verification file" "Copy was not approved."
  cp "$VERIFICATION_SOURCE" "$DESTINATION"
fi
cmp -s "$VERIFICATION_SOURCE" "$DESTINATION" || \
  fail "Verification file" "The copied file differs from the downloaded file."
record "Verification file" "verified" "Copied $VERIFICATION_NAME byte for byte into public/."

stage "Build, commit, and deploy"
BRANCH=$(git branch --show-current)
[[ "$BRANCH" == "main" ]] || \
  fail "Build and deployment" \
    "Run this wizard from main after issue #33 passes review. Current branch: $BRANCH"
git diff --check
npm run build
npm run lint
[[ -z "$(git diff --cached --name-only)" ]] || \
  fail "Build and deployment" "The Git index already contains staged changes. Unstage them and restart the wizard."
git add -- "public/$VERIFICATION_NAME"
if git diff --cached --quiet; then
  say "The verification file is already committed."
else
  confirm "Commit the exact Google verification file?" || \
    fail "Build and deployment" "The verification file was not committed."
  git commit -m "chore: add Search Console verification"
fi
[[ -z "$(git status --porcelain --untracked-files=no)" ]] || \
  fail "Build and deployment" "Tracked files are dirty after the verification-file commit."
confirm "Push main to deploy through Cloudflare Pages?" || \
  fail "Build and deployment" "Deployment push was not approved."
git push origin main
say "Wait for the production deployment to finish in Cloudflare Pages."
open_url "https://dash.cloudflare.com/"
confirm "Does the newest portfolio-2mj production deployment show Success?" || \
  fail "Build and deployment" "Cloudflare Pages did not show a successful production deployment."
require_200 "$PUBLIC_URL/"
require_200 "$PUBLIC_URL/$VERIFICATION_NAME"
record "Build and deployment" "verified" \
  "Build and lint passed. Main was pushed. The homepage and verification file returned HTTP 200."

stage "Verify ownership in Search Console"
open_url "https://search.google.com/search-console"
step "Select the $PUBLIC_URL/ property."
step "Return to the HTML file verification method."
step "Select Verify."
step "Google must report Ownership verified."
confirm "Does Search Console report Ownership verified?" || \
  fail "Search Console ownership" "Search Console did not report verified ownership."
record "Search Console ownership" "verified" "Emil confirmed ownership verified through $VERIFICATION_NAME."

stage "Submit and read the sitemap"
open_url "https://search.google.com/search-console/sitemaps"
step "Select the $PUBLIC_URL/ property if Search Console asks."
step "Under Add a new sitemap, enter sitemap.xml."
step "Select Submit."
step "Refresh the Sitemaps report."
step "The row for $PUBLIC_URL/sitemap.xml must show Success, and the last read date must be present."
confirm "Does the sitemap row show Success with a last read date?" || \
  fail "Sitemap" "Search Console did not show a successful sitemap read."
record "Sitemap" "verified" "Search Console shows sitemap.xml as submitted and read."

stage "Inspect the home page"
open_url "https://search.google.com/search-console"
step "Paste $PUBLIC_URL/ into the URL Inspection field."
step "Run Test live URL if Search Console offers it."
step "Select Request indexing."
step "Wait for the request confirmation."
confirm "Did Search Console confirm the indexing request?" || \
  fail "URL Inspection" "Search Console did not confirm the indexing request."
record "URL Inspection" "verified" \
  "URL Inspection ran for the home page. Search Console confirmed the indexing request."

stage "Import the site into Bing"
open_url "https://www.bing.com/webmasters/"
step "Sign in with the account that can access the Search Console property."
step "Select Import from Google Search Console."
step "Authorize read access when Google asks."
step "Select $PUBLIC_URL/ and complete the import."
step "Open the imported site in Bing Webmaster Tools."
confirm "Is $PUBLIC_URL/ visible as an imported Bing site?" || \
  fail "Bing import" "Bing did not show the imported site."
record "Bing import" "verified" "Emil confirmed the site is present after import from Search Console."

stage "Update the LinkedIn profile"
open_url "https://www.linkedin.com/in/emil-vladinov/"
step "Edit the intro section."
step "Set Location to Copenhagen, Capital Region, Denmark, or the current LinkedIn label for Copenhagen."
step "Open Contact info. Add $PUBLIC_URL/ as the website."
step "Open Add profile section, then Recommended, then Add featured."
step "Add $PUBLIC_URL/ as a Featured link and save it."
step "View the public profile. Confirm the Copenhagen location and both site links."
confirm "Does the public profile show Copenhagen, the Contact info URL, and the Featured link?" || \
  fail "LinkedIn profile" "The public LinkedIn profile does not show all required values."
record "LinkedIn profile" "verified" \
  "Emil confirmed Copenhagen plus Contact info and Featured links on the public profile."

stage "Update the GitHub profile"
open_url "https://github.com/settings/profile"
step "Set Website to $PUBLIC_URL/."
step "Set Location to exactly: Copenhagen, Denmark"
step "Save the profile."
open_url "https://github.com/emkataumre"
step "Confirm the public profile shows the website and exact location."
confirm "Does the public profile show both values?" || \
  fail "GitHub profile" "The public GitHub profile does not show both required values."
record "GitHub profile" "verified" "Emil confirmed website $PUBLIC_URL/ and location Copenhagen, Denmark."

stage "Run the live quality checks"
say "First, check the homepage and every fixed public asset."
for path in \
  "/" \
  "/favicon.ico" \
  "/icon.svg" \
  "/apple-touch-icon.png" \
  "/og.png" \
  "/robots.txt" \
  "/sitemap.xml" \
  "/fonts/InterVariable.woff2"
do
  require_200 "$PUBLIC_URL$path"
done

HOME_HTML=$(curl -sS "$PUBLIC_URL/")
ASSET_PATHS=$(printf '%s' "$HOME_HTML" | grep -oE '(src|href)="/assets/[^"]+"' | cut -d'"' -f2 | sort -u)
[[ -n "$ASSET_PATHS" ]] || fail "Live quality checks" "No built asset URL was found in the production HTML."
while IFS= read -r asset; do
  require_200 "$PUBLIC_URL$asset"
done <<< "$ASSET_PATHS"

open_url "$PUBLIC_URL/"
say "Use an incognito browser window with extensions disabled."
step "Open DevTools. Set the viewport to 1280 by 800. Reload and inspect the full page."
step "Set the viewport to 390 by 844. Reload and inspect the full page."
step "Emulate prefers-reduced-motion: reduce. Reload and inspect the full page."
step "At each size, confirm no clipped content, broken layout, or console error."
step "In Network, confirm no analytics request and no third-party script or font request."
step "Confirm Inter loads from /fonts/InterVariable.woff2."
step "Run Lighthouse in mobile mode. SEO must be 100."
step "Lighthouse must show no accessibility failure. The heading-order audit must pass."
step "Largest Contentful Paint must be at most 2.5 seconds. Cumulative Layout Shift must be at most 0.1."
open_url "https://search.google.com/test/rich-results?url=https%3A%2F%2Fportfolio-2mj.pages.dev%2F"
step "Run the Rich Results Test. It must report no structured-data error."
open_url "https://validator.schema.org/#url=https%3A%2F%2Fportfolio-2mj.pages.dev%2F"
step "Run the Schema Markup Validator. It must report no error."
confirm "Did every live quality check pass?" || \
  fail "Live quality checks" "At least one browser, Lighthouse, network, or structured-data check failed."
record "Live quality checks" "verified" \
  "Homepage and assets returned 200. Emil confirmed browser, Lighthouse, and data checks."

stage "Remove the stale retired route from edge cache"
PLAIN_CODE=$(status_code "$PUBLIC_URL/build-log")
SLASH_CODE=$(status_code "$PUBLIC_URL/build-log/")
BUSTER_CODE=$(status_code "$PUBLIC_URL/build-log/?issue-33-cache-check=$(date +%s)")
say "Current responses:"
say "    /build-log   -> HTTP $PLAIN_CODE"
say "    /build-log/  -> HTTP $SLASH_CODE"
say "    cache-busted -> HTTP $BUSTER_CODE"

if [[ "$PLAIN_CODE" != "404" || "$SLASH_CODE" != "404" ]]; then
  record "Retired routes" "pending" \
    "A purge is required. Codes: plain $PLAIN_CODE, slash $SLASH_CODE, cache-busted $BUSTER_CODE."
  warn "Both queryless retired URLs must return 404. A cache-busted 404 does not pass this gate."
  say "Cloudflare documents Purge Everything for stale Pages assets."
  say "Do not select the Pages Build cache Clear Cache control. It only clears build artifacts."
  open_url "https://dash.cloudflare.com/"
  step "Open the Cloudflare zone that serves this Pages hostname."
  step "Open Caching, then Configuration."
  step "Under Purge Cache, select Purge Everything."
  step "Confirm the purge."
  warn "If no zone exposes cache controls for the pages.dev hostname, stop here."
  warn "Use Cloudflare support or wait for the stale s-maxage entry to expire, then restart this wizard."
  confirm "Did Cloudflare confirm the served-content purge?" || \
    fail "Retired routes" "Cloudflare did not confirm the served-content purge."
  PLAIN_CODE=$(status_code "$PUBLIC_URL/build-log")
  SLASH_CODE=$(status_code "$PUBLIC_URL/build-log/")
fi

[[ "$PLAIN_CODE" == "404" && "$SLASH_CODE" == "404" ]] || \
  fail "Retired routes" \
    "After the purge, /build-log returned $PLAIN_CODE and /build-log/ returned $SLASH_CODE."
record "Retired routes" "verified" "Both queryless retired URL forms returned HTTP 404. No redirect was added."

stage "Update the map and close issue #33"
say "No accepted deferral exists for this issue."
say "Review the receipt before you change GitHub."
say "    $RECEIPT_FILE"
if rg -q '\| failed \|' "$RECEIPT_FILE"; then
  fail "Map and issue closure" "The receipt contains a failed event. Resolve it and run the wizard again."
fi
confirm "Did all eleven earlier gates pass in this run?" || \
  fail "Map and issue closure" "At least one required gate is still pending."
open_url "$REPO_URL/issues/1"
step "Edit the Decisions-so-far section of map issue #1."
step "Add a line for issue #33 with the live URL: $PUBLIC_URL/"
step "Save the map issue and confirm the live URL is visible."
open_url "$REPO_URL/issues/33"
step "Add a closing comment that links to the map and states that every issue #33 gate passed."
step "Close issue #33."
confirm "Is the map updated and issue #33 closed?" || \
  fail "Map and issue closure" "The map update or issue closure is not complete."
record "Map and issue closure" "verified" "Emil confirmed the live URL is on map issue #1 and issue #33 is closed."

finish
say "Receipt: $RECEIPT_FILE"
say "All issue #33 gates passed."
